// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Roomates.DataModel.Models;

namespace Roomates.DataModel.Migrations
{
    [DbContext(typeof(RoomatesDbContext))]
    [Migration("20201106131918_RoomatesMigrations")]
    partial class RoomatesMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Roomates.DataModel.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("Age")
                        .HasMaxLength(10);

                    b.Property<bool>("DoYouHaveSpace");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool>("Messages");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<long>("PhoneNumber")
                        .HasMaxLength(10);

                    b.Property<bool>("QuestionForRoomate");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new { Id = "1", Address = "New Address", Age = 23, DoYouHaveSpace = true, Email = "viktoriajovanovska@gmail.com", FullName = "Viktorija Jovanovska", Messages = true, Password = "`-?`;?'????F??", PhoneNumber = 707070L, QuestionForRoomate = true }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
